"""Persistence models.

Deliberately narrow. The operational world (flights, crew, rosters, duty
clocks) is a read-only snapshot loaded from JSON into ``app.core.World`` -- it
is never written, so mirroring it into tables would add a second source of
truth for no gain. What the database holds is everything the system *produces*:

  * agent runs, spans, facts and rule evaluations  -- the audit trail
  * conversations and messages                      -- multi-turn context
  * decisions and notifications                     -- what a controller did
  * alerts                                          -- what the watchers found
  * eval runs                                       -- correctness over time

The world tables are still generated (see ``etl.py``) for teams that want to
query the schedule with SQL, but nothing in the answer path depends on them.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.types import JSON


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    type_annotation_map = {dict[str, Any]: JSON, list: JSON}


# ==========================================================================
# World snapshot (generated by ETL; read path does not depend on these)
# ==========================================================================


class Station(Base):
    __tablename__ = "stations"
    code: Mapped[str] = mapped_column(String(3), primary_key=True)


class Aircraft(Base):
    __tablename__ = "aircraft"
    tail: Mapped[str] = mapped_column(String(16), primary_key=True)
    aircraft_type: Mapped[str] = mapped_column(String(16))
    seats: Mapped[int] = mapped_column(Integer)


class Flight(Base):
    __tablename__ = "flights"
    flight_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    flight_no: Mapped[str] = mapped_column(String(8), index=True)
    date: Mapped[Any] = mapped_column(Date, index=True)
    dep_station: Mapped[str] = mapped_column(String(3), index=True)
    arr_station: Mapped[str] = mapped_column(String(3), index=True)
    dep_utc: Mapped[datetime] = mapped_column(DateTime)
    arr_utc: Mapped[datetime] = mapped_column(DateTime)
    block_hours: Mapped[float] = mapped_column(Float)
    aircraft: Mapped[str] = mapped_column(String(16), index=True)
    aircraft_type: Mapped[str] = mapped_column(String(16))
    seats: Mapped[int] = mapped_column(Integer)

    __table_args__ = (Index("ix_flights_date_dep", "date", "dep_station"),)


class Crew(Base):
    __tablename__ = "crew"
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    name: Mapped[str] = mapped_column(String(64))
    rank: Mapped[str] = mapped_column(String(32), index=True)
    base: Mapped[str] = mapped_column(String(3), index=True)
    seniority: Mapped[int] = mapped_column(Integer)
    reachability_minutes: Mapped[int] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(String(16), index=True)


class CrewRating(Base):
    __tablename__ = "crew_ratings"
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    aircraft_type: Mapped[str] = mapped_column(String(16), primary_key=True)


class Pairing(Base):
    __tablename__ = "pairings"
    pairing_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    aircraft: Mapped[str] = mapped_column(String(16), index=True)


class PairingDay(Base):
    __tablename__ = "pairing_days"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    pairing_id: Mapped[str] = mapped_column(String(16), index=True)
    day_index: Mapped[int] = mapped_column(Integer)
    date: Mapped[Any] = mapped_column(Date, index=True)
    report_utc: Mapped[datetime] = mapped_column(DateTime)
    release_utc: Mapped[datetime] = mapped_column(DateTime)
    sectors: Mapped[int] = mapped_column(Integer)
    duty_hours: Mapped[float] = mapped_column(Float)
    flight_hours: Mapped[float] = mapped_column(Float)
    flight_ids: Mapped[list] = mapped_column(JSON)


class PairingCrew(Base):
    __tablename__ = "pairing_crew"
    pairing_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True, index=True)
    role: Mapped[str] = mapped_column(String(32))


class DutyClockDaily(Base):
    __tablename__ = "duty_clock_daily"
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    date: Mapped[Any] = mapped_column(Date, primary_key=True)
    duty_hours: Mapped[float] = mapped_column(Float)
    flight_hours: Mapped[float] = mapped_column(Float)


class DutyClockSummary(Base):
    __tablename__ = "duty_clock_summary"
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    as_of_utc: Mapped[datetime] = mapped_column(DateTime)
    duty_hours_7d: Mapped[float] = mapped_column(Float)
    flight_hours_28d: Mapped[float] = mapped_column(Float)
    last_rest_ended: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)


class ReserveAssignment(Base):
    __tablename__ = "reserve_assignments"
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    date: Mapped[Any] = mapped_column(Date, primary_key=True)
    base: Mapped[str] = mapped_column(String(3), index=True)
    oncall_start: Mapped[str] = mapped_column(String(5))
    oncall_end: Mapped[str] = mapped_column(String(5))


class Certification(Base):
    __tablename__ = "certifications"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    crew_id: Mapped[str] = mapped_column(String(16), index=True)
    cert_type: Mapped[str] = mapped_column(String(32))
    valid_from: Mapped[Any] = mapped_column(Date)
    valid_to: Mapped[Any] = mapped_column(Date, index=True)


class RuleRow(Base):
    __tablename__ = "rules"
    rule_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    text: Mapped[str] = mapped_column(Text)
    params: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)


class CostRate(Base):
    __tablename__ = "cost_rates"
    key: Mapped[str] = mapped_column(String(48), primary_key=True)
    value: Mapped[int] = mapped_column(Integer)
    currency: Mapped[str] = mapped_column(String(8))


class RiskSignalRow(Base):
    __tablename__ = "risk_signals"
    crew_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    as_of_utc: Mapped[datetime] = mapped_column(DateTime)
    score: Mapped[float] = mapped_column(Float, index=True)
    drivers: Mapped[list] = mapped_column(JSON)


# ==========================================================================
# Conversations
# ==========================================================================


class Conversation(Base):
    __tablename__ = "conversations"
    id: Mapped[str] = mapped_column(String(40), primary_key=True)
    title: Mapped[str] = mapped_column(String(200), default="")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

    messages: Mapped[list["Message"]] = relationship(
        back_populates="conversation", cascade="all, delete-orphan", order_by="Message.created_at"
    )


class Message(Base):
    __tablename__ = "messages"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[str] = mapped_column(
        ForeignKey("conversations.id", ondelete="CASCADE"), index=True
    )
    role: Mapped[str] = mapped_column(String(16))
    content: Mapped[str] = mapped_column(Text)
    answer_json: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    run_id: Mapped[str | None] = mapped_column(String(40), nullable=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)

    conversation: Mapped[Conversation] = relationship(back_populates="messages")


# ==========================================================================
# Observability
# ==========================================================================


class AgentRun(Base):
    __tablename__ = "agent_runs"
    run_id: Mapped[str] = mapped_column(String(40), primary_key=True)
    conversation_id: Mapped[str | None] = mapped_column(String(40), nullable=True, index=True)
    question: Mapped[str] = mapped_column(Text)
    intent: Mapped[str | None] = mapped_column(String(48), nullable=True, index=True)
    tier: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    plan_source: Mapped[str | None] = mapped_column(String(16), nullable=True)
    status: Mapped[str] = mapped_column(String(16), default="ok", index=True)
    abstained: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    #: None for direct simulation runs -- there was no narration to verify.
    verified: Mapped[bool | None] = mapped_column(Boolean, nullable=True, index=True)
    latency_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    tokens_in: Mapped[int] = mapped_column(Integer, default=0)
    tokens_out: Mapped[int] = mapped_column(Integer, default=0)
    span_count: Mapped[int] = mapped_column(Integer, default=0)
    tool_call_count: Mapped[int] = mapped_column(Integer, default=0)
    fact_count: Mapped[int] = mapped_column(Integer, default=0)
    started_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)


class AgentSpan(Base):
    __tablename__ = "agent_spans"
    span_id: Mapped[str] = mapped_column(String(40), primary_key=True)
    run_id: Mapped[str] = mapped_column(String(40), index=True)
    parent_span_id: Mapped[str | None] = mapped_column(String(40), nullable=True)
    name: Mapped[str] = mapped_column(String(64), index=True)
    type: Mapped[str] = mapped_column(String(16), index=True)
    started_at: Mapped[datetime] = mapped_column(DateTime)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    duration_ms: Mapped[float | None] = mapped_column(Float)
    status: Mapped[str] = mapped_column(String(16), default="ok")
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    input: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    output: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    input_hash: Mapped[str | None] = mapped_column(String(24), nullable=True)
    output_hash: Mapped[str | None] = mapped_column(String(24), nullable=True)
    attrs: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)


class FactRow(Base):
    __tablename__ = "fact_ledger"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String(40), index=True)
    fact_id: Mapped[str] = mapped_column(String(16))
    key: Mapped[str] = mapped_column(String(200))
    value: Mapped[str] = mapped_column(Text)
    unit: Mapped[str] = mapped_column(String(16), default="")
    source_span_id: Mapped[str | None] = mapped_column(String(40), nullable=True)
    source_tool: Mapped[str | None] = mapped_column(String(64), nullable=True)
    citation: Mapped[str] = mapped_column(String(64), default="")


class RuleEvaluation(Base):
    __tablename__ = "rule_evaluations"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String(40), index=True)
    span_id: Mapped[str | None] = mapped_column(String(40), nullable=True)
    rule_id: Mapped[str] = mapped_column(String(32), index=True)
    subject_crew_id: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    subject_date: Mapped[str | None] = mapped_column(String(10), nullable=True)
    verdict: Mapped[str] = mapped_column(String(16), index=True)
    actual: Mapped[float | None] = mapped_column(Float, nullable=True)
    limit_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    margin: Mapped[float | None] = mapped_column(Float, nullable=True)
    message: Mapped[str] = mapped_column(Text)
    arithmetic: Mapped[list] = mapped_column(JSON, default=list)


# ==========================================================================
# Actions & alerts
# ==========================================================================


class Decision(Base):
    __tablename__ = "decisions"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str | None] = mapped_column(String(40), nullable=True, index=True)
    kind: Mapped[str] = mapped_column(String(32), default="assignment")
    pairing_id: Mapped[str | None] = mapped_column(String(16), nullable=True)
    crew_id: Mapped[str | None] = mapped_column(String(16), nullable=True)
    option: Mapped[dict[str, Any]] = mapped_column(JSON)
    cost_inr: Mapped[int | None] = mapped_column(Integer, nullable=True)
    chosen_by: Mapped[str] = mapped_column(String(64), default="controller")
    status: Mapped[str] = mapped_column(String(16), default="applied", index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, index=True)


class Notification(Base):
    __tablename__ = "notifications"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    decision_id: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
    crew_id: Mapped[str] = mapped_column(String(16), index=True)
    channel: Mapped[str] = mapped_column(String(16), default="sms")
    body: Mapped[str] = mapped_column(Text)
    slots: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    status: Mapped[str] = mapped_column(String(16), default="draft", index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)


class Alert(Base):
    __tablename__ = "alerts"
    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    type: Mapped[str] = mapped_column(String(48), index=True)
    severity: Mapped[str] = mapped_column(String(16), index=True)
    title: Mapped[str] = mapped_column(String(200))
    detail: Mapped[str] = mapped_column(Text, default="")
    entity_ref: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    payload: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    suggested_question: Mapped[str | None] = mapped_column(String(300), nullable=True)
    state: Mapped[str] = mapped_column(String(16), default="open", index=True)
    detected_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, index=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)


class EvalRun(Base):
    __tablename__ = "eval_runs"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    suite: Mapped[str] = mapped_column(String(24), index=True)
    total: Mapped[int] = mapped_column(Integer)
    passed: Mapped[int] = mapped_column(Integer)
    pass_rate: Mapped[float] = mapped_column(Float)
    by_tier: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    report: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    duration_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, index=True)
